feat(api-gen): add deprecated flag to manifest, filter duplicates
angular/dev-infra pull request #1455
Opened 2023-10-20 00:30 UTC by jelbourn

Some symbol names appear more than once in the case of function overloads; this commit filters these duplicate entries and additionally adds a deprecated flag to the results.

2023-10-20 14:45 UTC, josephperrott approved these changes
LGTM Overall

Just one change please

2023-10-20 14:45 UTC, josephperrott commented on bazel/api-gen/manifest/index.ts
> +      if (seen.has(entry.name)) return false;
```suggestion
      if (seen.has(entry.name)) {
        return false;
      }
```

2023-10-20 22:05 UTC, jelbourn commented on bazel/api-gen/manifest/index.ts
> +      if (seen.has(entry.name)) return false;
Done

2023-10-20 22:08 UTC, jelbourn commented
@josephperrott the imaginary Paul in my head was looking at me with disapproving eyes for not having unit tests, so I've also added unit tests for this (which also involved refactoring the main logic out from `main.ts`). I also realized I had a bug where functions would be marked as deprecated if _any_ of the overloads were deprecated; fixed so that it only happens if they're _all_ marked deprecated.

2023-10-23 15:53 UTC, josephperrott requested changes

2023-10-24 21:21 UTC, jelbourn commented on bazel/api-gen/manifest/generate_manifest.ts
> +        entryLookup.get(lookupKey)?.push(entry);
Done (it doesn't really matter either way here)

2023-10-24 21:21 UTC, jelbourn commented on bazel/api-gen/manifest/generate_manifest.ts
> +      entryLookup.set(lookupKey, []);
Great catch, fixed

2023-10-27 15:17 UTC, josephperrott approved these changes
LGTM

2023-10-27 15:19 UTC, closed without merging